export default {
    title: 'P3X Redis UI',
    updater: {
        'checking-for-update': 'Ricerca aggiornamenti ...',
        'update-available': 'Download dell\'ultima versione ...',
        'update-not-available': 'Nessun nuovo aggiornamento disponibile.',
        error: (opts) => {
            return `Errore nell'aggiornamento automatico: ${opts.errorMessage}`
        },
        'download-progress': (opts) => {
            return 'Scaricato ' + opts.progressObj.percent + '%'
        },
        'update-downloaded': 'Aggiornamento scaricato. Puoi riavviare l\'app per aggiornare.'
    },
    button: {
      ok: 'OK',
    },
    message: {
        restart: 'Attendere, l\'applicazione si sta riavviando.',
    },
    menu: {
        main: {
            home: 'Home',
            console: 'Console',
            settings: 'Impostazioni',
            overview: 'Panoramica',
            quit: 'Esci',
        },
        edit: {
            title: 'Modifica',
            undo: 'Annulla',
            redo: 'Ripeti',
            cut: 'Taglia',
            copy: 'Copia',
            paste: 'Incolla',
            pasteandmatchstyle: 'Incolla e adatta lo stile',
            delete: 'Elimina',
            selectall: 'Seleziona tutto',
        },
        view: {
            title: 'Visualizza',
            reload: 'Ricarica',
            forcereload: 'Forza ricarica',
            toggledevtools: 'Attiva/Disattiva strumenti di sviluppo',
            resetzoom: 'Reimposta Zoom',
            zoomin: 'Ingrandisci',
            zoomout: 'Rimpicciolisci',
            togglefullscreen: 'Attiva/Disattiva schermo intero',
        },
        language: {
            title: 'Lingua / Language',
            auto: 'Auto (system)',
            translation: {
                bg: 'Български / Bulgarian',
                cs: 'Čeština / Czech',
                de: 'Deutsch / German',
                el: 'Ελληνικά / Greek',
                en: 'English',
                es: 'Español / Spanish',
                fr: 'Français / French',
                hu: 'Magyar / Hungarian',
                it: 'Italiano / Italian',
                ja: '日本語 / Japanese',
                nl: 'Nederlands / Dutch',
                pl: 'Polski / Polish',
                'pt-PT': 'Português / Portuguese',
                ro: 'Română / Romanian',
                ru: 'Русский / Russian',
                sk: 'Slovenčina / Slovak',
                sr: 'Српски / Serbian',
                sv: 'Svenska / Swedish',
                tr: 'Türkçe / Turkish',
                uk: 'Українська / Ukrainian',
                zn: '中文 / Chinese',
                ar: 'العربية / Arabic',
                az: 'Azərbaycanca / Azerbaijani',
                be: 'Беларуская / Belarusian',
                bn: 'বাংলা / Bengali',
                da: 'Dansk / Danish',
                et: 'Eesti / Estonian',
                fi: 'Suomi / Finnish',
                fil: 'Filipino / Filipino',
                he: 'עברית / Hebrew',
                hr: 'Hrvatski / Croatian',
                hy: 'Հայերեն / Armenian',
                id: 'Bahasa Indonesia / Indonesian',
                ka: 'ქართული / Georgian',
                kk: 'Қазақша / Kazakh',
                km: 'ខ្មែរ / Khmer',
                ko: '한국어 / Korean',
                ky: 'Кыргызча / Kyrgyz',
                lt: 'Lietuvių / Lithuanian',
                mk: 'Македонски / Macedonian',
                ms: 'Bahasa Melayu / Malay',
                ne: 'नेपाली / Nepali',
                no: 'Norsk / Norwegian',
                'pt-BR': 'Português (Brasil) / Portuguese (Brazil)',
                sl: 'Slovenščina / Slovenian',
                tg: 'Тоҷикӣ / Tajik',
                th: 'ไทย / Thai',
                vi: 'Tiếng Việt / Vietnamese',
                'zh-HK': '中文（香港） / Chinese (Hong Kong)',
                'zh-TW': '中文（台灣） / Chinese (Taiwan)',
                bs: 'Bosanski / Bosnian',
                si: 'සිංහල / Sinhala',
                sw: 'Kiswahili / Swahili',
                ta: 'தமிழ் / Tamil',
            }
        },
        settings: {
            title: 'Impostazioni',
            hideMenu: 'Nascondi il menu principale (mostra con ALT)',
            optionToHideMenuState: {
                yes: 'Dopo il riavvio, il menu sarà nascosto e visibile con ALT.',
            },
        },
        help: {
            changelog: 'Registro modifiche',
            download: 'Download',
            developer: 'Sviluppatore',
            checkUpdates: 'Controlla aggiornamenti',
        },
        donate: {
            title: 'Dona',
        }
    },
}
