export default {
    title: 'P3X Redis UI',
    updater: {
        'checking-for-update': 'Güncelleme kontrol ediliyor ...',
        'update-available': 'En son sürüm indiriliyor ...',
        'update-not-available': 'Yeni güncelleme mevcut değil.',
        error: (opts) => {
            return `Otomatik güncelleyici hatası: ${opts.errorMessage}`
        },
        'download-progress': (opts) => {
            return 'İndirildi ' + opts.progressObj.percent + '%'
        },
        'update-downloaded': 'Güncelleme indirildi. Güncellemek için uygulamayı yeniden başlatabilirsiniz.'
    },
    button: {
      ok: 'Tamam',
    },
    message: {
        restart: 'Lütfen bekleyin, uygulama yeniden başlatılıyor.',
    },
    menu: {
        main: {
            home: 'Ana Sayfa',
            console: 'Konsol',
            settings: 'Ayarlar',
            overview: 'Genel Bakış',
            quit: 'Çıkış',
        },
        edit: {
            title: 'Düzenle',
            undo: 'Geri Al',
            redo: 'Yinele',
            cut: 'Kes',
            copy: 'Kopyala',
            paste: 'Yapıştır',
            pasteandmatchstyle: 'Yapıştır ve stili eşleştir',
            delete: 'Sil',
            selectall: 'Tümünü seç',
        },
        view: {
            title: 'Görünüm',
            reload: 'Yeniden yükle',
            forcereload: 'Zorla yeniden yükle',
            toggledevtools: 'Geliştirici araçlarını aç/kapat',
            resetzoom: 'Yakınlaştırmayı sıfırla',
            zoomin: 'Yakınlaştır',
            zoomout: 'Uzaklaştır',
            togglefullscreen: 'Tam ekranı aç/kapat',
        },
        language: {
            title: 'Dil / Language',
            translation: {
                bg: "Български / Bulgarian",
                cs: "Čeština / Czech",
                de: "Deutsch / German",
                el: "Ελληνικά / Greek",
                en: "English",
                es: "Español / Spanish",
                fr: "Français / French",
                hu: "Magyar / Hungarian",
                it: "Italiano / Italian",
                ja: "日本語 / Japanese",
                nl: "Nederlands / Dutch",
                pl: "Polski / Polish",
                "pt-PT": "Português / Portuguese",
                ro: "Română / Romanian",
                ru: "Русский / Russian",
                sk: "Slovenčina / Slovak",
                sr: "Српски / Serbian",
                sv: "Svenska / Swedish",
                tr: "Türkçe / Turkish",
                uk: "Українська / Ukrainian",
                zn: "中文 / Chinese",
                ar: 'العربية / Arabic',
                az: 'Azərbaycanca / Azerbaijani',
                be: 'Беларуская / Belarusian',
                bn: 'বাংলা / Bengali',
                da: 'Dansk / Danish',
                et: 'Eesti / Estonian',
                fi: 'Suomi / Finnish',
                fil: 'Filipino / Filipino',
                he: 'עברית / Hebrew',
                hr: 'Hrvatski / Croatian',
                hy: 'Հայերեն / Armenian',
                id: 'Bahasa Indonesia / Indonesian',
                ka: 'ქართული / Georgian',
                kk: 'Қазақша / Kazakh',
                km: 'ខ្មែរ / Khmer',
                ko: '한국어 / Korean',
                ky: 'Кыргызча / Kyrgyz',
                lt: 'Lietuvių / Lithuanian',
                mk: 'Македонски / Macedonian',
                ms: 'Bahasa Melayu / Malay',
                ne: 'नेपाली / Nepali',
                no: 'Norsk / Norwegian',
                'pt-BR': 'Português (Brasil) / Portuguese (Brazil)',
                sl: 'Slovenščina / Slovenian',
                tg: 'Тоҷикӣ / Tajik',
                th: 'ไทย / Thai',
                vi: 'Tiếng Việt / Vietnamese',
                'zh-HK': '中文（香港） / Chinese (Hong Kong)',
                'zh-TW': '中文（台灣） / Chinese (Taiwan)',
                bs: 'Bosanski / Bosnian',
                si: 'සිංහල / Sinhala',
                sw: 'Kiswahili / Swahili',
                ta: 'தமிழ் / Tamil',
            }
        },
        settings: {
            title: 'Ayarlar',
            hideMenu: 'Ana menüyü gizle (ALT ile göster)',
            optionToHideMenuState: {
                yes: 'Yeniden başlatmadan sonra menü gizlenecek ve ALT ile gösterilecektir.',
            },
        },
        help: {
            changelog: 'Değişiklik günlüğü',
            download: 'İndir',
            developer: 'Geliştirici',
            checkUpdates: 'Güncellemeleri kontrol et',
        },
        donate: {
            title: 'Bağış Yap',
        }
    },
}
