{{- if .Values.ingress.enabled -}}
{{- $paths := .Values.ingress.paths -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: p3x-redis-ui-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: p3x-redis-ui
    helm.sh/chart: p3x-redis-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: p3x-redis-ui
    app.kubernetes.io/component:  {{ .Release.Name }}
{{- if .Values.ingress.labels }}
{{- toYaml .Values.ingress.labels | nindent 4 }}
{{- end }}
spec:
  rules:
  {{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p }}
            backend:
              serviceName: p3x-redis-ui-service
              servicePort: p3x-redis-ui
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p }}
            backend:
              serviceName: p3x-redis-ui-service
              servicePort: p3x-redis-ui
  {{- end -}}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}

