apiVersion: v1
kind: Service
metadata:
  name: p3x-redis-ui-service
  namespace: p3x-redis-ui
  labels:
    app.kubernetes.io/name: p3x-redis-ui-service
spec:
  ports:
  - port: 7843
    targetPort: p3x-redis-ui
    name: p3x-redis-ui
  selector:
    app.kubernetes.io/name: p3x-redis-ui